# SATRIA AI Enterprise Deployment Configuration
# Phase 4: Enterprise-grade cybersecurity platform deployment

apiVersion: v1
kind: ConfigMap
metadata:
  name: satria-enterprise-config
  namespace: satria-ai

deployment:
  profile: enterprise
  environment: production

  # High availability configuration
  high_availability:
    enabled: true
    replicas: 3
    auto_scaling:
      enabled: true
      min_replicas: 3
      max_replicas: 10
      target_cpu_utilization: 70
      target_memory_utilization: 80

  # Load balancing
  load_balancer:
    type: application
    ssl_termination: true
    health_checks:
      enabled: true
      interval: 30s
      timeout: 10s
      healthy_threshold: 2
      unhealthy_threshold: 3

  # Security configuration
  security:
    tls:
      enabled: true
      min_version: "1.2"
      cipher_suites:
        - "ECDHE-RSA-AES256-GCM-SHA384"
        - "ECDHE-RSA-AES128-GCM-SHA256"
        - "ECDHE-RSA-AES256-SHA384"

    authentication:
      type: enterprise_sso
      providers:
        - okta
        - azure_ad
        - saml2
      mfa_required: true
      session_timeout: 3600

    authorization:
      rbac_enabled: true
      policy_engine: opa
      audit_logging: true

    network_security:
      vpc_isolation: true
      private_subnets: true
      nat_gateway: true
      security_groups:
        - name: satria-api
          ports: [443, 80]
          sources: ["load_balancer"]
        - name: satria-internal
          ports: [8000, 8001, 5432, 6379]
          sources: ["satria-api", "satria-workers"]

# Infrastructure components
infrastructure:
  compute:
    api_servers:
      instance_type: c5.2xlarge
      count: 3
      cpu: 8
      memory: 16Gi
      storage: 100Gi

    worker_nodes:
      instance_type: m5.xlarge
      count: 5
      cpu: 4
      memory: 16Gi
      storage: 50Gi

    ai_processing:
      instance_type: p3.2xlarge
      count: 2
      gpu: 1
      cpu: 8
      memory: 61Gi
      storage: 200Gi

  storage:
    primary_database:
      type: postgresql
      version: "14"
      instance_class: db.r5.2xlarge
      storage: 1000Gi
      backup_retention: 30
      multi_az: true
      encryption: true

    cache:
      type: redis
      version: "7.0"
      instance_class: cache.r6g.xlarge
      cluster_mode: true
      num_cache_nodes: 3
      encryption_at_rest: true
      encryption_in_transit: true

    object_storage:
      type: s3
      bucket_encryption: AES256
      versioning: true
      lifecycle_policies:
        - transition_to_ia: 30
        - transition_to_glacier: 90
        - expiration: 2555  # 7 years for compliance

  monitoring:
    metrics:
      provider: prometheus
      retention: 30d
      high_availability: true

    logging:
      provider: elk_stack
      retention: 365d
      log_levels:
        - application: info
        - security: debug
        - audit: debug

    alerting:
      provider: pagerduty
      escalation_policies:
        - critical: 5m
        - high: 15m
        - medium: 1h

    apm:
      provider: datadog
      trace_sampling: 100%
      profiling: true

# Application configuration
application:
  api:
    workers: 4
    worker_connections: 1000
    keepalive_timeout: 65
    max_requests: 1000

  ai_agents:
    max_concurrent_sessions: 100
    session_timeout: 1800
    model_cache_size: 10Gi

  purple_team:
    max_concurrent_exercises: 10
    exercise_retention: 365d
    collaboration_history: 180d

  compliance:
    audit_retention: 2555d  # 7 years
    report_generation: daily
    alert_thresholds:
      - compliance_score: 85
      - control_failures: 5
      - audit_findings: 10

  performance:
    response_time_sla: 500ms
    availability_sla: 99.9%
    throughput_target: 1000rps

# Backup and disaster recovery
backup:
  strategy: 3-2-1
  frequency:
    database: hourly
    application_data: daily
    configuration: daily

  retention:
    daily: 30
    weekly: 12
    monthly: 12
    yearly: 7

  encryption: AES256
  compression: gzip

  disaster_recovery:
    rto: 2h  # Recovery Time Objective
    rpo: 1h  # Recovery Point Objective
    secondary_region: us-west-2
    replication: async

# Compliance and governance
compliance:
  frameworks:
    - soc2_type2
    - iso27001
    - gdpr
    - hipaa
    - pci_dss

  data_classification:
    public: no_encryption
    internal: encryption_at_rest
    confidential: encryption_at_rest_and_transit
    restricted: end_to_end_encryption

  retention_policies:
    audit_logs: 2555d
    security_events: 1095d
    user_data: 365d
    application_logs: 90d

  privacy:
    data_anonymization: true
    right_to_be_forgotten: true
    consent_management: true
    data_minimization: true

# Development and deployment
ci_cd:
  pipeline:
    build_timeout: 30m
    test_timeout: 45m
    deployment_timeout: 20m

  quality_gates:
    - unit_test_coverage: 80%
    - security_scan: pass
    - vulnerability_scan: pass
    - compliance_check: pass

  environments:
    development:
      auto_deploy: true
      approval_required: false

    staging:
      auto_deploy: false
      approval_required: true
      approvers: ["tech_lead", "security_team"]

    production:
      auto_deploy: false
      approval_required: true
      approvers: ["tech_lead", "security_team", "compliance_team"]
      deployment_window: "02:00-04:00 UTC"

# Enterprise integrations
integrations:
  siem:
    - splunk
    - qradar
    - sentinel

  itsm:
    - servicenow
    - jira_service_desk

  communication:
    - slack
    - microsoft_teams
    - email

  identity_providers:
    - active_directory
    - okta
    - azure_ad

  vulnerability_management:
    - qualys
    - rapid7
    - tenable

  threat_intelligence:
    - crowdstrike
    - recorded_future
    - anomali

# Cost optimization
cost_optimization:
  auto_scaling:
    enabled: true
    scale_down_cooldown: 300s
    scale_up_cooldown: 60s

  spot_instances:
    enabled: true
    percentage: 30
    instance_types: ["m5.large", "m5.xlarge"]

  reserved_instances:
    enabled: true
    term: 1_year
    payment_option: partial_upfront

  storage_optimization:
    intelligent_tiering: true
    lifecycle_policies: true
    compression: true

# Support and maintenance
support:
  tier: enterprise
  sla:
    response_time:
      critical: 15m
      high: 1h
      medium: 4h
      low: 24h

  maintenance_window:
    primary: "Sunday 02:00-04:00 UTC"
    emergency: "Any time with 24h notice"

  escalation:
    level1: operations_team
    level2: engineering_team
    level3: architecture_team
    level4: vendor_support